name: event-notification-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - discord.py==2.3.2
    - python-dotenv==1.0.0
    - line-bot-sdk==3.5.0
    - fastapi==0.109.0
    - uvicorn==0.25.0
    - supabase==2.1.0
    - postgrest==0.13.0
    - asyncio==3.4.3
    - aiohttp>=3.8.5,<3.9.0
    - pytest==7.4.4
    - pytest-asyncio==0.23.3
    - pytest-cov==4.1.0
    - pytest-mock==3.12.0
    - httpx>=0.24.0,<0.25.0  # supabaseの要件に合わせて修正